import { spawnSync } from "node:child_process";
import { join } from "node:path";
import {
  ensureDirectory,
  pathExists,
  makeExecutable,
  writeTextFile,
} from "./filesystem.js";
import {
  createDefaultProjectConfig,
  writeProjectConfig,
} from "./config.js";
import type {
  ProjectAnalysis,
} from "./init-scaffold.js";
import {
  renderGeneratedAgentsMarkdown,
  renderGeneratedConfigArtifacts,
  renderGeneratedRuleArtifacts,
  renderGeneratedScriptArtifacts,
  renderGeneratedScriptsReadmeMarkdown,
  renderGeneratedSkillArtifacts,
  renderGeneratedTemplateArtifacts,
  renderGeneratedWorkflowArtifacts,
  renderProjectAnalysis,
} from "./init-scaffold.js";
import type {
  InitializeProjectOptions,
  InitializeProjectResult,
  ScaffoldDirectory,
} from "./types.js";
import { resolveWorkspacePaths } from "./workspace.js";

const agentDirectories: readonly ScaffoldDirectory[] = [
  { path: ".flowness", description: "Flowness-managed project workspace" },
  { path: ".flowness/config", description: "Project-level configuration" },
  { path: ".flowness/issues", description: "Issue records" },
  { path: ".flowness/logs", description: "Append-only execution logs" },
  { path: ".flowness/workflows", description: "Workflow definitions" },
  { path: ".flowness/rules", description: "Global rules" },
  { path: ".flowness/skills", description: "Reusable skills" },
  { path: ".flowness/scripts", description: "Automation scripts" },
  { path: ".flowness/templates", description: "Template assets" },
  { path: ".flowness/prompts", description: "Prompt assets" },
  { path: ".flowness/settings", description: "Runtime settings" },
  { path: ".flowness/state", description: "Workflow and harness state" },
];

const agentReadmes: ReadonlyArray<{ path: string; title: string; body: string }> = [
  {
    path: ".flowness/README.md",
    title: ".flowness",
    body: "Flowness-managed project workspace for issues, logs, workflows, rules, skills, scripts, templates, prompts, and settings.",
  },
  {
    path: ".flowness/config/README.md",
    title: "config",
    body: "Project-level configuration files generated by Flowness.",
  },
  {
    path: ".flowness/issues/README.md",
    title: "issues",
    body: "Issue directories and issue-specific artifacts live here.",
  },
  {
    path: ".flowness/logs/README.md",
    title: "logs",
    body: "Append-only logs for every issue and workflow step live here.",
  },
  {
    path: ".flowness/prompts/README.md",
    title: "prompts",
    body: "Prompt assets live here.",
  },
  {
    path: ".flowness/settings/README.md",
    title: "settings",
    body: "Runtime settings and local project overrides live here.",
  },
];

const promptFiles: ReadonlyArray<{ path: string; content: string }> = [
  {
    path: ".flowness/prompts/core-agent.md",
    content: [
      "# Core Agent",
      "",
      "운영체제 규칙을 집행하는 기본 에이전트입니다.",
      "",
      "## Responsibilities",
      "- 이슈와 워크플로우를 항상 먼저 확인합니다.",
      "- 증거가 없으면 완료를 주장하지 않습니다.",
      "- 로그는 append-only로 유지합니다.",
      "",
      "## Output Contract",
      "- 다음 행동",
      "- 필요한 증거",
      "- 남은 리스크",
      "",
    ].join("\n"),
  },
  {
    path: ".flowness/prompts/planning-agent.md",
    content: [
      "# Planning Agent",
      "",
      "기획 전용 에이전트입니다.",
      "",
      "## Responsibilities",
      "- 요구사항을 구조화합니다.",
      "- 범위와 우선순위를 분리합니다.",
      "- 의사결정이 필요한 지점을 표시합니다.",
      "",
      "## Output Contract",
      "- 요구사항 요약",
      "- 범위",
      "- 질문 목록",
      "- 다음 이슈",
      "",
    ].join("\n"),
  },
  {
    path: ".flowness/prompts/review-agent.md",
    content: [
      "# Review Agent",
      "",
      "검증 전용 에이전트입니다.",
      "",
      "## Responsibilities",
      "- 반례를 먼저 찾습니다.",
      "- 증거가 없는 주장을 거부합니다.",
      "- 실패 시 blocking finding을 남깁니다.",
      "",
      "## Output Contract",
      "- 요약",
      "- 발견 사항",
      "- 차단 여부",
      "",
    ].join("\n"),
  },
  {
    path: ".flowness/prompts/research-agent.md",
    content: [
      "# Research Agent",
      "",
      "조사 전용 에이전트입니다.",
      "",
      "## Responsibilities",
      "- 신뢰 가능한 출처를 우선합니다.",
      "- 결론보다 근거를 남깁니다.",
      "- 비교 대상과 차이를 기록합니다.",
      "",
      "## Output Contract",
      "- 출처 목록",
      "- 비교 결과",
      "- 추천안",
      "",
    ].join("\n"),
  },
  {
    path: ".flowness/prompts/architecture-agent.md",
    content: [
      "# Architecture Agent",
      "",
      "설계 전용 에이전트입니다.",
      "",
      "## Responsibilities",
      "- 패키지 경계를 점검합니다.",
      "- 결합도와 확장성을 평가합니다.",
      "- 장기 리스크를 명시합니다.",
      "",
      "## Output Contract",
      "- 구조 요약",
      "- 위험 요소",
      "- 권장 변경",
      "",
    ].join("\n"),
  },
];

const scriptFiles: ReadonlyArray<{ path: string; content: string }> = [
  {
    path: ".flowness/scripts/find-fqcn.py",
    content: [
      "#!/usr/bin/env python3",
      "\"\"\"Find fully qualified names or references in the workspace.\"\"\"",
      "",
      "from __future__ import annotations",
      "",
      "import argparse",
      "import subprocess",
      "import sys",
      "from pathlib import Path",
      "",
      "def run_rg(pattern: str, root: str) -> int:",
      "    command = [\"rg\", \"-n\", \"--hidden\", \"--glob\", \"!**/node_modules/**\", pattern, root]",
      "    try:",
      "        completed = subprocess.run(command, check=False)",
      "        return completed.returncode",
      "    except FileNotFoundError:",
      "        return 127",
      "",
      "def main() -> int:",
      "    parser = argparse.ArgumentParser(description=\"Find references for a symbol or class name.\")",
      "    parser.add_argument(\"query\", help=\"Symbol or class name to search for\")",
      "    parser.add_argument(\"root\", nargs=\"?\", default=str(Path.cwd()), help=\"Workspace root\")",
      "    args = parser.parse_args()",
      "",
      "    code = run_rg(args.query, args.root)",
      "    if code == 127:",
      "        print(\"rg is not installed; please install ripgrep or run the search manually.\", file=sys.stderr)",
      "    return code",
      "",
      "if __name__ == \"__main__\":",
      "    raise SystemExit(main())",
      "",
    ].join("\n"),
  },
  {
    path: ".flowness/scripts/search-reference.py",
    content: [
      "#!/usr/bin/env python3",
      "\"\"\"Search references to a file name or term across the workspace.\"\"\"",
      "",
      "from __future__ import annotations",
      "",
      "import argparse",
      "import subprocess",
      "import sys",
      "from pathlib import Path",
      "",
      "def main() -> int:",
      "    parser = argparse.ArgumentParser(description=\"Search references across the workspace.\")",
      "    parser.add_argument(\"query\", help=\"Reference or keyword to search for\")",
      "    parser.add_argument(\"root\", nargs=\"?\", default=str(Path.cwd()), help=\"Workspace root\")",
      "    args = parser.parse_args()",
      "    command = [\"rg\", \"-n\", \"--hidden\", \"--glob\", \"!**/node_modules/**\", args.query, args.root]",
      "    try:",
      "        completed = subprocess.run(command, check=False)",
      "        return completed.returncode",
      "    except FileNotFoundError:",
      "        print(\"rg is not installed; please install ripgrep or run the search manually.\", file=sys.stderr)",
      "        return 127",
      "",
      "if __name__ == \"__main__\":",
      "    raise SystemExit(main())",
      "",
    ].join("\n"),
  },
  {
    path: ".flowness/scripts/check-md-size.py",
    content: [
      "#!/usr/bin/env python3",
      "\"\"\"Check Markdown files for oversized content.\"\"\"",
      "",
      "from __future__ import annotations",
      "",
      "import argparse",
      "from pathlib import Path",
      "",
      "def main() -> int:",
      "    parser = argparse.ArgumentParser(description=\"Check Markdown file size thresholds.\")",
      "    parser.add_argument(\"root\", nargs=\"?\", default=str(Path.cwd()), help=\"Workspace root\")",
      "    parser.add_argument(\"--max-lines\", type=int, default=400, help=\"Maximum allowed line count\")",
      "    parser.add_argument(\"--max-chars\", type=int, default=12000, help=\"Maximum allowed character count\")",
      "    args = parser.parse_args()",
      "",
      "    root = Path(args.root)",
      "    violations = []",
      "    for path in root.rglob(\"*.md\"):",
      "        try:",
      "            text = path.read_text(encoding=\"utf-8\")",
      "        except OSError:",
      "            continue",
      "        line_count = text.count(\"\\n\") + 1 if text else 0",
      "        char_count = len(text)",
      "        if line_count > args.max_lines or char_count > args.max_chars:",
      "            violations.append(f\"{path}: {line_count} lines, {char_count} chars\")",
      "",
      "    if violations:",
      "        print(\"Markdown size violations detected:\")",
      "        for violation in violations:",
      "            print(f\"- {violation}\")",
      "        return 1",
      "",
      "    print(\"No Markdown size violations detected.\")",
      "    return 0",
      "",
      "if __name__ == \"__main__\":",
      "    raise SystemExit(main())",
      "",
    ].join("\n"),
  },
];

function renderReadme(title: string, body: string): string {
  return `# ${title}\n\n${body}\n`;
}

function renderAgentsMarkdown(analysis: ProjectAnalysis): string {
  return renderGeneratedAgentsMarkdown(analysis);
}

function ensureGitRepository(rootDir: string): { readonly initialized: boolean; readonly warning: string | null } {
  const status = spawnSync("git", ["rev-parse", "--is-inside-work-tree"], {
    cwd: rootDir,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });

  if (status.status === 0) {
    return {
      initialized: false,
      warning: null,
    };
  }

  const init = spawnSync("git", ["init"], {
    cwd: rootDir,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });

  if (init.status !== 0) {
    throw new Error(`Unable to initialize git repository: ${init.stderr?.trim() || init.stdout?.trim() || "unknown error"}`);
  }

  return {
    initialized: true,
    warning: "Git repository was initialized because this project root did not already contain one.",
  };
}

export async function initializeProject(
  options: InitializeProjectOptions,
): Promise<InitializeProjectResult> {
  const rootDir = join(options.rootDir);
  const force = options.force ?? false;
  const paths = resolveWorkspacePaths(rootDir);
  const createdDirectories: string[] = [];
  const createdFiles: string[] = [];
  const skippedFiles: string[] = [];
  const warnings: string[] = [];

  const gitResult = ensureGitRepository(rootDir);
  if (gitResult.warning !== null) {
    warnings.push(gitResult.warning);
  }

  for (const directory of agentDirectories) {
    const directoryPath = join(rootDir, directory.path);
    if (await ensureDirectory(directoryPath)) {
      createdDirectories.push(directory.path);
    }
  }

  const legacyWorkspaceDetected = await pathExists(paths.legacyAgentDir)
    || await pathExists(paths.legacyCodexDir)
    || await pathExists(paths.legacyConfigPath)
    || await pathExists(join(rootDir, ".agent", "config", "project.yaml"));
  if (legacyWorkspaceDetected) {
    warnings.push("Legacy .agent workspace files were detected. Flowness will use .flowness/ for new files; migrate the old workspace when ready.");
  }

  const alreadyInitialized = await pathExists(paths.configPath) || legacyWorkspaceDetected;
  const analysis = await renderProjectAnalysis(rootDir, options.projectName);
  const projectName = analysis.projectName;

  const config = createDefaultProjectConfig(projectName);
  const configWriteResult = await writeProjectConfig(rootDir, config, force);
  if (configWriteResult === "written") {
    createdFiles.push(".flowness/config/project.yaml");
  } else {
    skippedFiles.push(".flowness/config/project.yaml");
  }

  const agentsPath = join(rootDir, "AGENTS.md");
  const agentsWriteResult = await writeTextFile(
    agentsPath,
    renderAgentsMarkdown(analysis),
    force,
  );
  if (agentsWriteResult === "written") {
    createdFiles.push("AGENTS.md");
  } else {
    skippedFiles.push("AGENTS.md");
  }

  for (const readme of agentReadmes) {
    const readmePath = join(rootDir, readme.path);
    const readmeWriteResult = await writeTextFile(
      readmePath,
      renderReadme(readme.title, readme.body),
      force,
    );
    if (readmeWriteResult === "written") {
      createdFiles.push(readme.path);
    } else {
      skippedFiles.push(readme.path);
    }
  }

  for (const promptFile of promptFiles) {
    const promptWriteResult = await writeTextFile(
      join(rootDir, promptFile.path),
      promptFile.content,
      force,
    );
    if (promptWriteResult === "written") {
      createdFiles.push(promptFile.path);
    } else {
      skippedFiles.push(promptFile.path);
    }
  }

  for (const configFile of renderGeneratedConfigArtifacts(analysis)) {
    const configWriteResult = await writeTextFile(
      join(rootDir, configFile.path),
      configFile.content,
      force,
    );
    if (configWriteResult === "written") {
      createdFiles.push(configFile.path);
    } else {
      skippedFiles.push(configFile.path);
    }
  }

  const scriptsReadmeWriteResult = await writeTextFile(
    join(rootDir, ".flowness/scripts/README.md"),
    renderGeneratedScriptsReadmeMarkdown(analysis),
    force,
  );
  if (scriptsReadmeWriteResult === "written") {
    createdFiles.push(".flowness/scripts/README.md");
  } else {
    skippedFiles.push(".flowness/scripts/README.md");
  }

  for (const scriptFile of renderGeneratedScriptArtifacts(analysis)) {
    const scriptWriteResult = await writeTextFile(
      join(rootDir, scriptFile.path),
      scriptFile.content,
      force,
    );
    if (scriptWriteResult === "written") {
      createdFiles.push(scriptFile.path);
    } else {
      skippedFiles.push(scriptFile.path);
    }
  }

  for (const ruleFile of renderGeneratedRuleArtifacts(analysis)) {
    const ruleWriteResult = await writeTextFile(
      join(rootDir, ruleFile.path),
      ruleFile.content,
      force,
    );
    if (ruleWriteResult === "written") {
      createdFiles.push(ruleFile.path);
    } else {
      skippedFiles.push(ruleFile.path);
    }
  }

  for (const skillFile of renderGeneratedSkillArtifacts(analysis)) {
    const skillWriteResult = await writeTextFile(
      join(rootDir, skillFile.path),
      skillFile.content,
      force,
    );
    if (skillWriteResult === "written") {
      createdFiles.push(skillFile.path);
    } else {
      skippedFiles.push(skillFile.path);
    }
  }

  for (const templateFile of renderGeneratedTemplateArtifacts(analysis)) {
    const templateWriteResult = await writeTextFile(
      join(rootDir, templateFile.path),
      templateFile.content,
      force,
    );
    if (templateWriteResult === "written") {
      createdFiles.push(templateFile.path);
    } else {
      skippedFiles.push(templateFile.path);
    }
  }

  for (const workflowFile of renderGeneratedWorkflowArtifacts(analysis)) {
    const workflowWriteResult = await writeTextFile(
      join(rootDir, workflowFile.path),
      workflowFile.content,
      force,
    );
    if (workflowWriteResult === "written") {
      createdFiles.push(workflowFile.path);
    } else {
      skippedFiles.push(workflowFile.path);
    }
  }

  for (const scriptFile of scriptFiles) {
    const scriptWriteResult = await writeTextFile(
      join(rootDir, scriptFile.path),
      scriptFile.content,
      force,
    );
    await makeExecutable(join(rootDir, scriptFile.path));
    if (scriptWriteResult === "written") {
      createdFiles.push(scriptFile.path);
    } else {
      skippedFiles.push(scriptFile.path);
    }
  }

  return {
    rootDir,
    projectName,
    alreadyInitialized,
    gitInitialized: gitResult.initialized,
    warnings,
    createdDirectories,
    createdFiles,
    skippedFiles,
  };
}
